### ISSUE TITLE
Ember CLI version locked to yarn.lock contents

### ISSUE THREAD

**Issue by boztek** [ember-cli/create-ember-app#1]
This project will need to be updated as new versions of ember-cli land.

**Comment by rwjblue** [comment]
Not sure why? The released packages already allows 2.15.0 (via the `^2.0.0` dep)...

**Comment by locks** [comment]
Hey @boztek! Thanks for the contribution but I agree with @rwjblue, we should already covered by the current dependencies.

**Comment by boztek** [comment]
Quite right!

For context the original problem was an error: "ember-cli@2.13.0: The engine "node" is incompatible with this module." when trying to "yarn create ember-app".

It seems the global yarn.lock was keeping my version locked to 2.13 between node version upgrades / ember-cli installs etc. If this happens to someone else a "yarn global remove ember-cli" might be required to get out of the funk as you'll be locked to whichever ^2.0.0 satisfying version you already have in your global yarn.lock.

As a side note, for me at least, the ember-cli lib used for "yarn create ember-app" apps is stuck to major version of whichever ember-cli version is in global yarn.lock too just for extra fun.
